services:
  app:
    image: andromoney-webfrontend:latest 
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./example-data/:/app/data/
    environment:
      FLASH_SECRET_KEY: ${FLASH_SECRET_KEY}
      GOOGLE_DRIVE_SHARE_URL: ${GOOGLE_DRIVE_SHARE_URL}